### PR TITLE
Update 2022 c2

### PR DESCRIPTION
**Pull request by JunAishima**

### CODE REVIEW

**Comment by mrakitin** [comment]
We probably should get the latest CI config here to make sure the kafka instantiation passes.

**Comment by mrakitin** [comment]
We probably should get ht elatest CI config here to make sure the kafka instantiation passes.

**Review by mrakitin — COMMENTED** [review]
I fixed the CI failures by using the newer configs (also fixed the case of TLA in the configs).

I think it'd make sense to merge https://github.com/NSLS-II/profile-collection-ci/pull/30 first, then change the reference here, and merge this PR.

**Comment by JunAishima** [comment]
have renamed the CI branch to main

**Comment by mrakitin** [comment]
Power-cycled to trigger the CI runs.

**Comment by mrakitin** [comment]
Manually submitted https://dev.azure.com/nsls2/profile_collections/_build/results?buildId=3926&view=results, as it did not pick up the new ref after merging the https://github.com/NSLS-II/profile-collection-ci/pull/30 PR.

**Review by mrakitin — APPROVED** [review]
Looks good to me, the CI tests are passing now.

**Review by AbbyGi — APPROVED** [review]

**Pull request merged**
