### PR TITLE
MNT: add root kwarg to tiff writer

### PR DESCRIPTION
**Pull request by tacaswell**
I have grave concerns that images are being written to `/tmp/`

attn @arkilic

### CODE REVIEW

**Comment by ghost** [comment]
Bruno is sensible enough to know the issues regarding writing files to /tmp. Is this your work in progress to get the camera to work @brunoseivam ?

**Comment by brunoseivam** [comment]
This was done when we were testing this feature and there was no networked filesystem on that computer. In practice those instances with the TIFF plugin are not being used at all. **Maybe I'll even remove them to speed up the startup time.**

**Comment by ghost** [comment]
See @tacaswell, he is very sensible.

**Comment by tacaswell** [comment]
If you do not need the images it is probably a good idea to comment out the tiff plugins and remove them from the read attrs.

**Comment by hhslepicka** [comment]
@tacaswell it would be good to have https://github.com/NSLS-II/ophyd/pull/326 for cases like this one where you have the plugin at your object but you can decide to use it or not.

**Comment by ghost** [comment]
@hhslepicka you seem bored
come-back-your

**Comment by hhslepicka** [comment]
89hanhg

**Pull request merged**
